# Generated by Django 2.0.10 on 2019-03-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_company', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('contacts', models.CharField(max_length=200)),
            ],
        ),
    ]
